### ISSUE TITLE
NullPointerException at com.spotify.oauth2.reports.ExtentLogger.info(ExtentLogger.java:39)

### ISSUE THREAD

**Issue by lucas-nguyen-17** [rajatt95/MasterRestAssuredFramework#1]
I run the test `ShouldBeAbleToCreateAPlaylist`, get error `NullPointerException`. I guess problem here:

- You only declared a `ThreadLocal<ExtentTest> extentTest` but haven't created `ExtentTest` instance and set to this `ThreadLocal`

Full stacktrace:

```
Re-newing Token........
Request method:	POST
Request URI:	https://accounts.spotify.com/api/token
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	refresh_token=AQAA4NY58s9oRvQoo6NpPvtZ38BhVu2STD8Fdii1-QIbeXgaYXbkcXo3mnMEdAvMuZvn6tEDXZC9zz1J552Um1N5wfZ4CEkexRb6oy-xCFMvq2_DiNh6SNomzADu85HvU6E
				grant_type=refresh_token
				client_secret=fa0a167372fb4d8ebdc84c3db543b92c
				client_id=568d41bc66f5436cb72d09bb4c6f5f6d
Path params:	<none>
Headers:		Accept=*/*
				Content-Type=application/x-www-form-urlencoded; charset=ISO-8859-1
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
HTTP/1.1 200 OK
date: Tue, 19 Oct 2021 02:08:26 GMT
content-type: application/json
vary: Accept-Encoding
set-cookie: __Host-device_id=AQDjOeilHBuheTAMl84-MylXpdjgKw0kz4a6iEN7f2Q_LB0Ji9re9lJln2GrP202ZH7VGN_X7AYzaHSE_ek1cYsqChajB27V3aM;Version=1;Path=/;Max-Age=2147483647;Secure;HttpOnly;SameSite=Lax
set-cookie: sp_tr=false;Version=1;Domain=accounts.spotify.com;Path=/;Secure;SameSite=Lax
sp-trace-id: 699dc282eed3c8b1
content-encoding: gzip
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
server: envoy
Via: HTTP/2 edgeproxy, 1.1 google
Alt-Svc: clear
Transfer-Encoding: chunked

{
    "access_token": "BQDk02Hg1JWicXaVfD8pBTTCGsX-bz6B_lHj9eiX5UBAJ8AcSL73m9Fk1913_hrdSIhCBx5KoFHZFeaxXTmHrLxD5ozytvPTMGFSMWVqk4k6w1bZBHrMWeyPxtlpxQOIb93zp1MpximC6Nbq6jGNV9INahDrwtMo_HqZbb-EeGG7FhnhL0Fx8NgFNDf6xiIasRW6N3fa-g2JJNEE4PpBkll4oohLRILvUQMuIDtMMET7",
    "token_type": "Bearer",
    "expires_in": 3600,
    "scope": "playlist-read-private playlist-read-collaborative playlist-modify-private playlist-modify-public"
}
java.lang.NullPointerException
	at com.spotify.oauth2.reports.ExtentLogger.info(ExtentLogger.java:39)
	at com.spotify.oauth2.api.RestResource.printDetailsInExtentReport(RestResource.java:29)
	at com.spotify.oauth2.api.RestResource.postAccount(RestResource.java:55)
	at com.spotify.oauth2.api.TokenManager.renewToken(TokenManager.java:63)
	at com.spotify.oauth2.api.TokenManager.getToken(TokenManager.java:28)
	at com.spotify.oauth2.api.applicationApi.PlaylistApi.post(PlaylistApi.java:25)
	at com.spotify.oauth2.tests.PlaylistTests_OC.ShouldBeAbleToCreateAPlaylist(PlaylistTests_OC.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

java.lang.RuntimeException: ABORT!! Failed to get Token

	at com.spotify.oauth2.api.TokenManager.getToken(TokenManager.java:43)
	at com.spotify.oauth2.api.applicationApi.PlaylistApi.post(PlaylistApi.java:25)
	at com.spotify.oauth2.tests.PlaylistTests_OC.ShouldBeAbleToCreateAPlaylist(PlaylistTests_OC.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

**Comment by rajatt95** [comment]
You need to run the test case(s) using the testng.xml file as configurations for ExtentReport have been done there in the ListenerClass.java. We need to tell TestNG that I'm using the TestNG interface(s). So that TestNG can consider them at the time of  execution.
